modified: README.md | added: hw-12/decorators.py
bassdarkside/prjctr-hw pull request #12
Opened 2023-09-03 22:25 UTC by bassdarkside

**Домашня робота** № _12_
Оскільки дедлайн, зробив тільки обовʼязкові завдання.
Додаткові буду додавати за можливості.

2023-09-04 10:41 UTC, bielanm requested changes

2023-09-04 10:41 UTC, bielanm commented on hw-12/decorators.py
> +            key = list(args[0].keys())[0]
ось цього не треба робити, бо в тебе функція може не приймати параметрів взагалі і тоді в тебе випаде помилка в обробці помилки, зроби просто print(e).

2023-09-05 10:21 UTC, bielanm requested changes

2023-09-05 10:21 UTC, bielanm commented on hw-12/decorators.py
> +        return func(*args, **kwargs)
Ось тут зайвий виклик `func(*args, **kwargs)`

2023-09-05 10:21 UTC, bielanm commented on hw-12/decorators.py
> +            params_name = list(params_annotations.keys())[i]
`list(params_annotations.keys())` краще винести з циклу в якусь змінну

2023-09-05 10:21 UTC, bielanm commented on hw-12/decorators.py
> +            params_name = list(params_annotations.keys())[i]
при чому зробити це не у функції `wrapper()` а в функцію `check_types`, щоб воно не створювалося на кожен виклик задекорованої функції

2023-09-05 10:21 UTC, bielanm commented on hw-12/decorators.py
> +            raise TypeError("Permission denied")
тут краще Exception спеціальний, або хоча б `ValueError`

2023-09-05 11:23 UTC, bassdarkside commented on hw-12/decorators.py
> +            raise TypeError("Permission denied")
Тобто непотрібно переривати виконання коду і просто зробити прінт?

2023-09-06 21:00 UTC, bielanm approved these changes

2023-09-07 08:22 UTC, merged