added: hw-9
bassdarkside/prjctr-hw pull request #7
Opened 2023-08-24 12:04 UTC by bassdarkside

Перше завдання:

- hw-9/hello.py
- hw-9/main.py

Друге завдання:

- hw-9/np_samples.py
- hw-9/requirements.txt
- hw-9/screenshot.png

2023-08-24 12:07 UTC, bassdarkside commented on hw-9/requirements.txt
> +numpy==1.25.2
✅

2023-08-24 14:53 UTC, bielanm requested changes
Привіт!

Загалом ок, маленький комент залишив, і також видали картинку - вона не потрібна для історії, того, на майбутнє, її краще додавати в сам пулл реквест (там де коментарі).

2023-08-24 14:53 UTC, bielanm commented on hw-9/requirements.txt
> +numpy==1.25.2
Дивись, загалом ти зробив те що від тебе просили, але краще буде, якщо в проєкті будуть описуватися ті залежності які напряму використовуються - в тебе це тільки `numpy` все інше це вже файли з твого оточення.


того зроби краще:
```
pip freeze | grep numpy > requirements.txt
```

2023-08-25 17:47 UTC, bielanm approved these changes

2023-08-25 17:53 UTC, bielanm commented
Привіт!
Апрувнув ПР, але для того, щоб тобі його замержити - треба порезолвити конфлікти.

Для цього локально:
1. переключись на мейн: `git checkout main`
2. впевнись, що гілка мейн знаходиться в такому ж стан, що і її версія на гітхабі: `git pull`
3. повернись на свою гілку: `git checkout hw-9`
4. зроби ребейз на мейн (почитай в інтернетіку що значить ця команда): `git rebase main`
5. в тебе повинне зʼявитися повідомлення про конфлікти
6.  перевір файли в яких вони є (червоні повинні бути): `git status`
7. пофікси конфлікти (в тебе це наче тільки README.md)
8. підтвердь що ти пофіксив конфлікти в файлі: `git add README.md (або інші файли)`
9. продовжи ребейз: `git rebase --continue`
10. запуш зміни: `git push` - повинна бути помилка
10. запуш зміни з форсом: `git push -f` 🙂

2023-08-25 19:52 UTC, bassdarkside commented
> Привіт! Апрувнув ПР, але для того, щоб тобі його замержити - треба порезолвити конфлікти.
> 
> Для цього локально:
> 
> 1. переключись на мейн: `git checkout main`
> 2. впевнись, що гілка мейн знаходиться в такому ж стан, що і її версія на гітхабі: `git pull`
> 3. повернись на свою гілку: `git checkout hw-9`
> 4. зроби ребейз на мейн (почитай в інтернетіку що значить ця команда): `git rebase main`
> 5. в тебе повинне зʼявитися повідомлення про конфлікти
> 6. перевір файли в яких вони є (червоні повинні бути): `git status`
> 7. пофікси конфлікти (в тебе це наче тільки README.md)
> 8. підтвердь що ти пофіксив конфлікти в файлі: `git add README.md (або інші файли)`
> 9. продовжи ребейз: `git rebase --continue`
> 10. запуш зміни: `git push` - повинна бути помилка
> 11. запуш зміни з форсом: `git push -f` 🙂

Спрацювало! Дякую!

2023-08-25 19:59 UTC, merged