added: hw-10
bassdarkside/prjctr-hw pull request #8
Opened 2023-08-29 11:32 UTC by bassdarkside

Привіт! Кожне завдання я поклав у окрему теку.

1. generate_txt
2. create_and_copy
3. score_csv
4. high_scores

2023-08-31 08:44 UTC, bielanm requested changes

2023-08-31 08:44 UTC, bielanm commented on hw-10/create_and_copy/create_and_copy.py
> +    return cp_data(filename, data)
Краще винеси цей виклик з функції, бо в тебе функція називається `create_file` і вона спочатку створює файл, а потім ще робить якусь незрозуміло роботу.

2023-08-31 08:44 UTC, bielanm commented on hw-10/create_and_copy/create_and_copy.py
> +        create_file(filename, data)
Ось цього не треба робити, тут просто виведи повідомлення, що файлу немає - помилка.
Бо в тебе мало того, що функція `cp_data` , що повинна створити копію файла по факту створить сам файл копію якого мала зробити, так ще й у випадку якоїсь помилки в функції create_file - буде безкінечна рекурсія `create_file - cp_data - FileNotFoundError - create_file - cp_data - FileNotFoundError` ...

2023-08-31 08:44 UTC, bielanm commented on hw-10/generate_txt/files/A.txt
> +46
Повидаляй також всі файли, що генеруються кодом.

2023-08-31 08:44 UTC, bielanm commented on hw-10/generate_txt/generate_txt.py
> +    int_list = make_rand_num(len(alphabet), rand_range)
`int_list = random.sample(range(rand_range), len(alphabet))` не треба створювати функцію, якщо воно тобі не зменшує кількість повторюваного коду і ніяк не інкапсулює логіку, а замість того робить просто прямий виклик у якусь іншу функцію.

2023-08-31 08:44 UTC, bielanm commented on hw-10/score_csv/score_csv.py
> +        writer = csv.writer(file)
а навіщо ти ту повторно створюєш `writer`?

2023-08-31 08:44 UTC, bielanm commented on hw-10/score_csv/score_csv.py
> +players = [["Josh", 0], ["Luke", 0], ["Kate", 0], ["Mark", 0], ["Mary", 0]]
для таких каунтерів структура даних dict більше підходить

2023-08-31 08:44 UTC, bielanm commented on hw-10/high_scores/high_scores.py
> +        top_scopes = sorted(lines[-5:], key=lambda top: top[1], reverse=True)
Твоя программа повинна читати cvs файл і записати max значення для кожного гравця, а зараз ти просто береш останні 5 рядків і сортуєш їх.

2023-08-31 13:03 UTC, bassdarkside commented on hw-10/score_csv/score_csv.py
> +players = [["Josh", 0], ["Luke", 0], ["Kate", 0], ["Mark", 0], ["Mary", 0]]
Я розглядав варіант зі словником, але у завданні було сказано створити список і я відштовхувався від цього.

_Create a **list** with 5 players names after that simulate 100 rounds for each player._

2023-08-31 21:16 UTC, bielanm commented on hw-10/score_csv/score_csv.py
> +players = [["Josh", 0], ["Luke", 0], ["Kate", 0], ["Mark", 0], ["Mary", 0]]
ну там список не в сенсі структури даних а слова "список")

2023-09-02 21:25 UTC, bielanm commented on hw-10/high_scores.py
> +        for player_name, highest_score in sort_hi_scores:
можна замінити на .writerows()

2023-09-04 10:38 UTC, bielanm approved these changes

2023-09-04 12:01 UTC, merged