Gif search
bassdarkside/prjctr-hw pull request #9
Opened 2023-08-30 09:20 UTC by bassdarkside

Домашня робота № 11
Привіт! Бот можна знайти в телеграмі за імʼям `gifler_bot`
- gif_search
- bot_telegram

2023-08-31 10:01 UTC, bielanm requested changes

2023-08-31 10:01 UTC, bielanm commented on gif_search/gif_search.py
> +    response = gif_request(*args)
Винеси це з функції, бо в тебе знову build_output відповідає не за побудову виводу, а ще якісь взагалі не повʼязані з виводом речі.

2023-09-02 21:59 UTC, bielanm approved these changes

2023-09-02 21:59 UTC, bielanm commented on bot_telegram/gifler_bot.py
> +    response = gif_request(*args)
те саме

2023-09-02 22:01 UTC, bielanm requested changes

2023-09-02 22:01 UTC, bielanm commented on bot_telegram/gifler_bot.py
> +    response = gif_request(*args)
маю на увазі: функція повинна відповідати за щось одне, тому gif_request треба винести звідси

2023-09-03 07:58 UTC, bassdarkside commented on bot_telegram/gifler_bot.py
> +    response = gif_request(*args)
Затупив і у файлі з ботом внести ці зміни

2023-09-04 10:17 UTC, bielanm approved these changes

2023-09-04 12:05 UTC, merged